### ISSUE TITLE
Screenshots are not saved

### ISSUE THREAD

**Issue by joshas** [flathub/org.scummvm.ScummVM#24]
Pressing <kbd>Alt + s</kbd> should take a screenshot and save it. This doesn't work in Flatpak version, as default screenshot path on Linux is `~/Pictures/ScummVM Screenshots` and ScummVM Flatpak has access only to `~/Documents`. While ScummVM informs that `Saved screenshot '{filename}.png' in current directory`, it cannot be find anywhere on device.

**Comment by AsciiWolf** [comment]
Thanks for reporting this! I will try looking at the issue when I have some free time.
