### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.scummvm.ScummVM#30]
Since the ScummVM Flatpak is an official one, it would be great if it could be verified.

Here are more details about verified apps: https://beta.flathub.org/about

/cc @lotharsm (You will probably need push rights to this repository first. These can be assigned to you by Flathub admins if you agree.)

**Comment by AsciiWolf** [comment]
@hfiguiere @barthalion Can you please add @lotharsm as a collaborator of this repo? Thanks!

**Comment by AsciiWolf** [comment]
Ah, sorry, I did not realize this. Hopefully @barthalion or @TingPing will be able to assign the permissions.

**Comment by barthalion** [comment]
Hey @lotharsm, just invited you. You will need to log out and in at beta.flathub.org to refresh available apps once you accept the invite.

**Comment by lotharsm** [comment]
Thank you very much, @barthalion! I'm going to start the verification process now.

**Comment by lotharsm** [comment]
The verification is now complete. :-)
